name: Notificar a ntfy.sh al hacer push en main

on:
  push:
    branches:
      - main

jobs:
  enviar-alerta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Ejecutar el programa (opcional)
        run: node app.js

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -d "Nuevo push realizado en main 🚨" ntfy.sh/devops-itla
